services:
  app:
    build:
      context: .
      dockerfile: backend_compose_dockerfile
    ports:
      - "8002:8082"
    environment:
      - RUNNING_IN_DOCKER=true
      - EXTERNAL_HOST=${PORTAL_BACKEND_HOST_IP:-localhost}
      - EXTERNAL_PORT=${MINIO_PORT:-8004}
      - EXTERNAL_SCHEME=${EXTERNAL_SCHEME:-}
    restart: unless-stopped
    volumes:
      - digitaltwins_portal_datasets:/annotator_gui_backend/data
    networks:
      - digitaltwins

volumes:
  digitaltwins_portal_datasets:
    external: true

networks:
  digitaltwins:
    external: true
    name: digitaltwins