services:
  app:
    build:
      context: .
      dockerfile: backend_compose_dockerfile
    environment:
      - RUNNING_IN_DOCKER=true
      - EXTERNAL_HOST=${PORTAL_BACKEND_HOST_IP:-localhost}
      - EXTERNAL_PORT=${MINIO_PORT:-8004}
      - EXTERNAL_SCHEME=${EXTERNAL_SCHEME:-}
      - USE_SSL=${USE_SSL:-false}
    restart: unless-stopped
    volumes:
      - digitaltwins_portal_datasets:/annotator_gui_backend/data
      - annotator_outputs:/annotator_gui_backend/outputs
    networks:
      - digitaltwins

volumes:
  digitaltwins_portal_datasets:
    external: true
  annotator_outputs:
    driver: local
networks:
  digitaltwins:
    external: true
    name: digitaltwins
